apiVersion: v1
kind: Service
metadata:
  labels:
    app: paymentmicroservice
  name: payment-service
spec:
  ports:
  - protocol: TCP
    port: 8082
    targetPort: 8082
  selector:
    app: paymentmicroservice
  type: LoadBalancer
status:
  loadBalancer: {}
